//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEPRevitPlagin.SecondaryCommand.LangResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EEPRevitPlagin.SecondaryCommand.LangResources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something didn’t work out. Keep calm and order!.
        /// </summary>
        public static string _Error_messages {
            get {
                return ResourceManager.GetString(" Error_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Models manually.
        /// </summary>
        public static string Add_models_manually {
            get {
                return ResourceManager.GetString("Add_models_manually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save model\nstate.
        /// </summary>
        public static string AnalyzeSourceModelCommand_Title {
            get {
                return ResourceManager.GetString("AnalyzeSourceModelCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the state of the model.
        /// </summary>
        public static string AnalyzeSourceModelCommand_Tooltip {
            get {
                return ResourceManager.GetString("AnalyzeSourceModelCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AleksandrPidlozhevich/EEP_Revit_Plagin.
        /// </summary>
        public static string AnalyzeSourceModelCommand_Url {
            get {
                return ResourceManager.GetString("AnalyzeSourceModelCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arch.
        /// </summary>
        public static string Architectural_PanelName {
            get {
                return ResourceManager.GetString("Architectural_PanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base material.
        /// </summary>
        public static string Base_material {
            get {
                return ResourceManager.GetString("Base_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building walls.
        /// </summary>
        public static string Building_walls {
            get {
                return ResourceManager.GetString("Building_walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By linked file.
        /// </summary>
        public static string By_linked_file {
            get {
                return ResourceManager.GetString("By_linked_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change plugin language.
        /// </summary>
        public static string Change_plugin_language {
            get {
                return ResourceManager.GetString("Change plugin language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witch\nbroom.
        /// </summary>
        public static string ChangeTypeCopyPropertisCommand_Title {
            get {
                return ResourceManager.GetString("ChangeTypeCopyPropertisCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes item type and copies all properties.
        /// </summary>
        public static string ChangeTypeCopyPropertisCommand_Tooltip {
            get {
                return ResourceManager.GetString("ChangeTypeCopyPropertisCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AleksandrPidlozhevich/EEP_Revit_Plagin.
        /// </summary>
        public static string ChangeTypeCopyPropertisCommand_Url {
            get {
                return ResourceManager.GetString("ChangeTypeCopyPropertisCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Models&apos;\nChanges.
        /// </summary>
        public static string CheckModelChangesCommand_Title {
            get {
                return ResourceManager.GetString("CheckModelChangesCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the linked models for any changes.
        /// </summary>
        public static string CheckModelChangesCommand_Tooltip {
            get {
                return ResourceManager.GetString("CheckModelChangesCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AleksandrPidlozhevich/EEP_Revit_Plagin.
        /// </summary>
        public static string CheckModelChangesCommand_Url {
            get {
                return ResourceManager.GetString("CheckModelChangesCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option:.
        /// </summary>
        public static string Choose_an_option {
            get {
                return ResourceManager.GetString("Choose_an_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose folder.
        /// </summary>
        public static string Choose_folder {
            get {
                return ResourceManager.GetString("Choose_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a room!.
        /// </summary>
        public static string Choose_room {
            get {
                return ResourceManager.GetString("Choose_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine all .nwc to one .nwd file.
        /// </summary>
        public static string Combine_all_nwc_to_one_nwd_file {
            get {
                return ResourceManager.GetString("Combine_all_nwc_to_one_nwd_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create wall finish.
        /// </summary>
        public static string CreateWallFinish {
            get {
                return ResourceManager.GetString("CreateWallFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting holes.
        /// </summary>
        public static string Cutting_holes {
            get {
                return ResourceManager.GetString("Cutting_holes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct insulation\ncheck.
        /// </summary>
        public static string DuctInsulationCheckCommand_Title {
            get {
                return ResourceManager.GetString("DuctInsulationCheckCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking the insulation of ducts and fittings.
        /// </summary>
        public static string DuctInsulationCheckCommand_Tooltip {
            get {
                return ResourceManager.GetString("DuctInsulationCheckCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AleksandrPidlozhevich/EEP_Revit_Plagin.
        /// </summary>
        public static string DuctInsulationCheckCommand_Url {
            get {
                return ResourceManager.GetString("DuctInsulationCheckCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Selected Models.
        /// </summary>
        public static string Export_selected_models {
            get {
                return ResourceManager.GetString("Export_selected_models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Graphics\nElements Find.
        /// </summary>
        public static string FindOverrideViewElementsCommand_Title {
            get {
                return ResourceManager.GetString("FindOverrideViewElementsCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find override graphics elements in current view.
        /// </summary>
        public static string FindOverrideViewElementsCommand_Tooltip {
            get {
                return ResourceManager.GetString("FindOverrideViewElementsCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AleksandrPidlozhevich/EEP_Revit_Plagin.
        /// </summary>
        public static string FindOverrideViewElementsCommand_Url {
            get {
                return ResourceManager.GetString("FindOverrideViewElementsCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish height.
        /// </summary>
        public static string Finish_height {
            get {
                return ResourceManager.GetString("Finish_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish type.
        /// </summary>
        public static string Finish_type {
            get {
                return ResourceManager.GetString("Finish_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Change.
        /// </summary>
        public static string Font_Change {
            get {
                return ResourceManager.GetString("Font_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change\nfont.
        /// </summary>
        public static string FontChangingCommand_Title {
            get {
                return ResourceManager.GetString("FontChangingCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the font in the project and annotations..
        /// </summary>
        public static string FontChangingCommand_Tooltip {
            get {
                return ResourceManager.GetString("FontChangingCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\\The-dc\00.0 инициатива инжпроект\20 БИБЛИОТЕКА\BIM_Библиотека\Revit\Плагины\EEP\About\FontChanging\FontChanging.pdf&quot;.
        /// </summary>
        public static string FontChangingCommand_Url {
            get {
                return ResourceManager.GetString("FontChangingCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the current file.
        /// </summary>
        public static string For_the_current_file {
            get {
                return ResourceManager.GetString("For_the_current_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greeting.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IFC view name contains.
        /// </summary>
        public static string IFC_view_contains {
            get {
                return ResourceManager.GetString("IFC_view_contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement\nlintels.
        /// </summary>
        public static string InstallationDoorWindowLintelsCommand_Title {
            get {
                return ResourceManager.GetString("InstallationDoorWindowLintelsCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement of jumpers over windows and doors.
        /// </summary>
        public static string InstallationDoorWindowLintelsCommand_Tooltip {
            get {
                return ResourceManager.GetString("InstallationDoorWindowLintelsCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\The-dc\00.0 инициатива инжпроект\20 БИБЛИОТЕКА\BIM_Библиотека\Revit\Плагины\EEP\About\Размезение перемычек над окнами и дверьми.pdf.
        /// </summary>
        public static string InstallationDoorWindowLintelsCommand_Url {
            get {
                return ResourceManager.GetString("InstallationDoorWindowLintelsCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageChange.
        /// </summary>
        public static string LanguageChangeCommand_Title {
            get {
                return ResourceManager.GetString("LanguageChangeCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageChange.
        /// </summary>
        public static string LanguageChangeCommand_Tooltip {
            get {
                return ResourceManager.GetString("LanguageChangeCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AleksandrPidlozhevich/EEPRevitPlagin.
        /// </summary>
        public static string LanguageChangeCommand_Url {
            get {
                return ResourceManager.GetString("LanguageChangeCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked file not found!.
        /// </summary>
        public static string Linked_file_not_found {
            get {
                return ResourceManager.GetString("Linked_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lintels.
        /// </summary>
        public static string Lintels {
            get {
                return ResourceManager.GetString("Lintels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet\nrenumbering.
        /// </summary>
        public static string ListNumberingCommand_Title {
            get {
                return ResourceManager.GetString("ListNumberingCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To extract Sheet Number and add it to the list.
        /// </summary>
        public static string ListNumberingCommand_Tooltip {
            get {
                return ResourceManager.GetString("ListNumberingCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\The-dc\00.0 инициатива инжпроект\20 БИБЛИОТЕКА\BIM_Библиотека\Revit\Плагины\EEP\About\Нумерация листов.pdf.
        /// </summary>
        public static string ListNumberingCommand_Url {
            get {
                return ResourceManager.GetString("ListNumberingCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEP.
        /// </summary>
        public static string MEP_PanelName {
            get {
                return ResourceManager.GetString("MEP_PanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging walls.
        /// </summary>
        public static string Merging_walls {
            get {
                return ResourceManager.GetString("Merging_walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare two\nmodels.
        /// </summary>
        public static string ModelCompareCommand_Title {
            get {
                return ResourceManager.GetString("ModelCompareCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare this model to the source model.
        /// </summary>
        public static string ModelCompareCommand_Tooltip {
            get {
                return ResourceManager.GetString("ModelCompareCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AleksandrPidlozhevich/EEP_Revit_Plagin.
        /// </summary>
        public static string ModelCompareCommand_Url {
            get {
                return ResourceManager.GetString("ModelCompareCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Navisworks view name contains.
        /// </summary>
        public static string Navisworks_view_contains {
            get {
                return ResourceManager.GetString("Navisworks_view_contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off\nanalytical model.
        /// </summary>
        public static string OffAnalyticsModelCommand_Title {
            get {
                return ResourceManager.GetString("OffAnalyticsModelCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off analytical model.
        /// </summary>
        public static string OffAnalyticsModelCommand_Tooltip {
            get {
                return ResourceManager.GetString("OffAnalyticsModelCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com.
        /// </summary>
        public static string OffAnalyticsModelCommand_Url {
            get {
                return ResourceManager.GetString("OffAnalyticsModelCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off model analytics group.
        /// </summary>
        public static string OffAnalyticsModelGroupCommand_Title {
            get {
                return ResourceManager.GetString("OffAnalyticsModelGroupCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off model analytics group.
        /// </summary>
        public static string OffAnalyticsModelGroupCommand_Tooltip {
            get {
                return ResourceManager.GetString("OffAnalyticsModelGroupCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com.
        /// </summary>
        public static string OffAnalyticsModelGroupCommand_Url {
            get {
                return ResourceManager.GetString("OffAnalyticsModelGroupCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart Revit for the changes to take effect.
        /// </summary>
        public static string Please_restart_Revit_for_the_changes_to_take_effect {
            get {
                return ResourceManager.GetString("Please_restart_Revit_for_the_changes_to_take_effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic\nwand.
        /// </summary>
        public static string PropertiesCopyCommand_Title {
            get {
                return ResourceManager.GetString("PropertiesCopyCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying element parameters.
        /// </summary>
        public static string PropertiesCopyCommand_Tooltip {
            get {
                return ResourceManager.GetString("PropertiesCopyCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AleksandrPidlozhevich/EEP_Revit_Plagin.
        /// </summary>
        public static string PropertiesCopyCommand_Url {
            get {
                return ResourceManager.GetString("PropertiesCopyCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property copying.
        /// </summary>
        public static string Property_copying {
            get {
                return ResourceManager.GetString("Property_copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehost.
        /// </summary>
        public static string ReHostHolesCommand_Title {
            get {
                return ResourceManager.GetString("ReHostHolesCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehost.
        /// </summary>
        public static string ReHostHolesCommand_Tooltip {
            get {
                return ResourceManager.GetString("ReHostHolesCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com.
        /// </summary>
        public static string ReHostHolesCommand_Url {
            get {
                return ResourceManager.GetString("ReHostHolesCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling in\nrevisions сlouds.
        /// </summary>
        public static string RevisionCloudsCommand_Title {
            get {
                return ResourceManager.GetString("RevisionCloudsCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling in revisions сlouds.
        /// </summary>
        public static string RevisionCloudsCommand_Tooltip {
            get {
                return ResourceManager.GetString("RevisionCloudsCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com.
        /// </summary>
        public static string RevisionCloudsCommand_Url {
            get {
                return ResourceManager.GetString("RevisionCloudsCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revit Server - Export Models.
        /// </summary>
        public static string Revit_Server_Export_Models {
            get {
                return ResourceManager.GetString("Revit_Server_Export_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revit Version.
        /// </summary>
        public static string Revit_Version {
            get {
                return ResourceManager.GetString("Revit_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revit Server\nExport.
        /// </summary>
        public static string RevitServerExportCommand_Title {
            get {
                return ResourceManager.GetString("RevitServerExportCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export model from Revit Server.
        /// </summary>
        public static string RevitServerExportCommand_Tooltip {
            get {
                return ResourceManager.GetString("RevitServerExportCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\\The-dc\00.0 инициатива инжпроект\20 БИБЛИОТЕКА\BIM_Библиотека\Revit\Плагины\EEP\About\Выгрузка Моделей с сервера.pdf&quot;.
        /// </summary>
        public static string RevitServerExportCommand_Url {
            get {
                return ResourceManager.GetString("RevitServerExportCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room boundary.
        /// </summary>
        public static string Room_boundary {
            get {
                return ResourceManager.GetString("Room_boundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to walls of the room.
        /// </summary>
        public static string RoomBoundaryLinesCommand_Title {
            get {
                return ResourceManager.GetString("RoomBoundaryLinesCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string RoomBoundaryLinesCommand_Tooltip {
            get {
                return ResourceManager.GetString("RoomBoundaryLinesCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com.
        /// </summary>
        public static string RoomBoundaryLinesCommand_Url {
            get {
                return ResourceManager.GetString("RoomBoundaryLinesCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as:.
        /// </summary>
        public static string Save_as {
            get {
                return ResourceManager.GetString("Save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reordering.
        /// </summary>
        public static string ScheduleRowCounterCommand_Title {
            get {
                return ResourceManager.GetString("ScheduleRowCounterCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add row numbers to the schedule.
        /// </summary>
        public static string ScheduleRowCounterCommand_Tooltip {
            get {
                return ResourceManager.GetString("ScheduleRowCounterCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AleksandrPidlozhevich/EEP_Revit_Plagin.
        /// </summary>
        public static string ScheduleRowCounterCommand_Url {
            get {
                return ResourceManager.GetString("ScheduleRowCounterCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a linked file!.
        /// </summary>
        public static string Select_a_linked_file {
            get {
                return ResourceManager.GetString("Select_a_linked_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item to copy properties to or click Esc to complete..
        /// </summary>
        public static string Select_copy_properties_or_Esc {
            get {
                return ResourceManager.GetString("Select_copy_properties_or_Esc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language :.
        /// </summary>
        public static string Select_Language {
            get {
                return ResourceManager.GetString("Select Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the item from which to copy properties.
        /// </summary>
        public static string Select_the_ite_from_which_to_copy_properties {
            get {
                return ResourceManager.GetString("Select_the_ite_from_which_to_copy_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected item could not be retrieved..
        /// </summary>
        public static string Selected_item_not_retrieved {
            get {
                return ResourceManager.GetString("Selected_item_not_retrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        public static string Server_IP {
            get {
                return ResourceManager.GetString("Server_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong! Please click the \&quot;Wall finish properties\&quot; button and select an option!&quot;.
        /// </summary>
        public static string Something_wrong_WallFinishProperties {
            get {
                return ResourceManager.GetString("Something_wrong!WallFinishProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regret! Cutting openings in walls through the API appeared only in the 2021 version!.
        /// </summary>
        public static string Sorry_сutting_openings_in_walls_through_the_API_appeared_only_in_the_2021_version {
            get {
                return ResourceManager.GetString("Sorry_сutting_openings_in_walls_through_the_API_appeared_only_in_the_2021_version" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export specification\nfields.
        /// </summary>
        public static string SpecificationExportCommand_Title {
            get {
                return ResourceManager.GetString("SpecificationExportCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecificationExport.
        /// </summary>
        public static string SpecificationExportCommand_Tooltip {
            get {
                return ResourceManager.GetString("SpecificationExportCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com.
        /// </summary>
        public static string SpecificationExportCommand_Url {
            get {
                return ResourceManager.GetString("SpecificationExportCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural.
        /// </summary>
        public static string Structural_PanelName {
            get {
                return ResourceManager.GetString("Structural_PanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall finish properties.
        /// </summary>
        public static string Wall_finish_properties {
            get {
                return ResourceManager.GetString("Wall_finish_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall finishing.
        /// </summary>
        public static string WallFinishCreatorCommand_Title {
            get {
                return ResourceManager.GetString("WallFinishCreatorCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create wall finishes along room contours from a linked file.
        /// </summary>
        public static string WallFinishCreatorCommand_Tooltip {
            get {
                return ResourceManager.GetString("WallFinishCreatorCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\\The-dc\00.0 инициатива инжпроект\20 БИБЛИОТЕКА\BIM_Библиотека\Revit\Плагины\EEP\About\WallFinishCreator\WallFinishCreator.pdf&quot;.
        /// </summary>
        public static string WallFinishCreatorCommand_Url {
            get {
                return ResourceManager.GetString("WallFinishCreatorCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall finish\nproperties.
        /// </summary>
        public static string WallFinishCreatorPropertiesCommand_Title {
            get {
                return ResourceManager.GetString("WallFinishCreatorPropertiesCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting the option to create a finish from a linked file or from the current file.
        /// </summary>
        public static string WallFinishCreatorPropertiesCommand_Tooltip {
            get {
                return ResourceManager.GetString("WallFinishCreatorPropertiesCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\The-dc\00.0 инициатива инжпроект\20 БИБЛИОТЕКА\BIM_Библиотека\Revit\Плагины\EEP\About\WallFinishCreator\WallFinishCreator.pdf.
        /// </summary>
        public static string WallFinishCreatorPropertiesCommand_Url {
            get {
                return ResourceManager.GetString("WallFinishCreatorPropertiesCommand_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сhoose a font.
        /// </summary>
        public static string Сhoose_a_font {
            get {
                return ResourceManager.GetString("Сhoose a font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сonnect to server.
        /// </summary>
        public static string Сonnect_to_server {
            get {
                return ResourceManager.GetString("Сonnect_to_server", resourceCulture);
            }
        }
    }
}
